#!/bin/sh
cat << __EOC__
$ ./configure  '--with-openssl=yes' '--enable-smartalloc' '--with-postgresql' '--with-db-name=bacula' '--with-db-user=bacula' '--with-db-password=9DMQ80w3WXTTBIg6DyasxRYC8TohHdM3LpH' '--with-db-port=5432' '--with-working-dir=/var/lib/bacula' '--with-pid-dir=/var/run/bacula' '--with-logdir=/var/log/bacula' '--with-readline=/usr/include/readline' '--disable-conio' '--enable-lockmgr' '--with-scriptdir=/etc/bacula/scripts' 'CFLAGS=-g -Wall'

Configuration on Thu Sep 25 09:26:51 BRT 2014:

   Host:		    x86_64-unknown-linux-gnu -- debian 7.6
   Bacula version:	    Bacula 7.0.5 (28 July 2014)
   Source code location:    .
   Install binaries:	    /sbin
   Install libraries:	    /usr/lib
   Install config files:    /etc/bacula
   Scripts directory:	    /etc/bacula/scripts
   Archive directory:	    /tmp
   Working directory:	    /var/lib/bacula
   PID directory:	    /var/run/bacula
   Subsys directory:	    /var/run/subsys
   Man directory:	    ${datarootdir}/man
   Data directory:	    /usr/share
   Plugin directory:	    /usr/lib
   C Compiler:		    gcc 4.7.2-5)
   C++ Compiler:	    /usr/bin/g++ 4.7.2-5)
   Compiler flags:	     -g -Wall -fno-strict-aliasing -fno-exceptions -fno-rtti
   Linker flags:	     
   Libraries:		    -lpthread -ldl -ldl 
   Statically Linked Tools: no
   Statically Linked FD:    no
   Statically Linked SD:    no
   Statically Linked DIR:   no
   Statically Linked CONS:  no
   Database backends:	    PostgreSQL
   Database port:	    5432
   Database name:	    bacula
   Database user:	    bacula

   Job Output Email:	    root@localhost
   Traceback Email:	    root@localhost
   SMTP Host Address:	    localhost

   Director Port:	    9101
   File daemon Port:	    9102
   Storage daemon Port:     9103

   Director User:	    
   Director Group:	    
   Storage Daemon User:     
   Storage DaemonGroup:     
   File Daemon User:	    
   File Daemon Group:	    

   Large file support:	    yes
   Bacula conio support:    no -lreadline -lhistory -ltinfo
   readline support:	    yes 
   TCP Wrappers support:    no 
   TLS support: 	    yes
   Encryption support:	    yes
   ZLIB support:	    yes
   LZO support: 	    no
   enable-smartalloc:	    yes
   enable-lockmgr:	    yes
   bat support: 	    no
   client-only: 	    no
   build-dird:		    yes
   build-stored:	    yes
   Plugin support:	    yes
   AFS support: 	    no
   ACL support: 	    no
   XATTR support:	    yes
   systemd support:	    no 
   Batch insert enabled:    PostgreSQL

  
__EOC__
